"""
Backend test for Mentor Portal endpoints.
Tests:
  - POST /api/bookings/{booking_id}/confirm
  - POST /api/bookings/{booking_id}/decline
  - POST /api/mentor/sessions
  - GET  /api/mentor/sessions/me
Regression:
  - GET /api/bookings/me
  - GET /api/notifications
  - GET /api/mentors/{mentor_id}/reviews
"""
import os
import sys
import time
import json
import requests
from datetime import datetime, timezone, timedelta

BASE = "https://hiring-mvvm.preview.emergentagent.com/api"
MENTOR_EMAIL = "mentor01@test.com"
MENTOR_PASS = "TestPass@123"
STUDENT_EMAIL = "student01@test.com"
STUDENT_PASS = "TestPass@123"
OTHER_MENTOR_EMAIL = "mentor02@test.com"
OTHER_MENTOR_PASS = "TestPass@123"

results = []


def _record(name, ok, status, body, note=""):
    results.append({
        "endpoint": name,
        "status_code": status,
        "pass": ok,
        "body_sample": (str(body)[:400] if body is not None else None),
        "note": note,
    })
    flag = "✅" if ok else "❌"
    print(f"{flag} [{status}] {name}  {note}")


def login(email, pwd):
    r = requests.post(f"{BASE}/auth/login", json={"email": email, "password": pwd}, timeout=20)
    assert r.status_code == 200, f"login {email} -> {r.status_code} {r.text}"
    return r.json()


def auth_headers(token):
    return {"Authorization": f"Bearer {token}"}


def main():
    # ---- 1. Login ----
    mentor = login(MENTOR_EMAIL, MENTOR_PASS)
    student = login(STUDENT_EMAIL, STUDENT_PASS)
    other_mentor = None
    try:
        other_mentor = login(OTHER_MENTOR_EMAIL, OTHER_MENTOR_PASS)
    except Exception as e:
        print(f"(optional) other mentor login skipped: {e}")

    mentor_token = mentor["access_token"]
    mentor_id = mentor["user"]["id"]
    student_token = student["access_token"]
    student_id = student["user"]["id"]

    print(f"\nMentor id: {mentor_id} ({mentor['user']['role']}, status={mentor['user'].get('mentor_status')})")
    print(f"Student id: {student_id} ({student['user']['role']})")

    # ---- 2. GET /bookings/me as mentor (regression baseline) ----
    r = requests.get(f"{BASE}/bookings/me", headers=auth_headers(mentor_token), timeout=20)
    bookings = (r.json() or {}).get("bookings", []) if r.status_code == 200 else []
    _record("GET /bookings/me (mentor)", r.status_code == 200, r.status_code, bookings[:1] if bookings else [],
            note=f"{len(bookings)} bookings")

    # ---- 3. Create a fresh booking from the student to mentor01 to ensure we have a known target ----
    # Backend currently sets new bookings to 'confirmed' — but the confirm endpoint
    # still flips status to confirmed (idempotent OK). For decline we want a new booking.
    slot_start = (datetime.now(timezone.utc) + timedelta(days=2)).isoformat()
    slot_end = (datetime.now(timezone.utc) + timedelta(days=2, hours=1)).isoformat()
    create_payload = {
        "mentor_id": mentor_id,
        "slot_start_iso": slot_start,
        "slot_end_iso": slot_end,
        "topic": "MentorPortalTest — Career Guidance",
        "notes": "Auto-generated by backend_test_mentor_portal.py",
    }
    cr = requests.post(f"{BASE}/bookings", json=create_payload, headers=auth_headers(student_token), timeout=20)
    _record("POST /bookings (student creates booking for mentor)", cr.status_code == 200, cr.status_code, cr.text[:300])
    if cr.status_code != 200:
        print("Cannot continue without creating booking; aborting.")
        return summarize()
    booking = cr.json()
    booking_id = booking.get("id")
    print(f"Created booking_id={booking_id}, status={booking.get('status')}")

    # ---- 4. POST /bookings/{id}/confirm as mentor ----
    rc = requests.post(f"{BASE}/bookings/{booking_id}/confirm", headers=auth_headers(mentor_token), timeout=20)
    confirm_ok = rc.status_code == 200 and (rc.json() or {}).get("ok") is True \
        and (rc.json() or {}).get("booking", {}).get("status") == "confirmed"
    _record("POST /bookings/{id}/confirm (mentor owner)", confirm_ok, rc.status_code, rc.text[:300])

    # ---- 5. Confirm permission: student should get 403 ----
    rs = requests.post(f"{BASE}/bookings/{booking_id}/confirm", headers=auth_headers(student_token), timeout=20)
    _record("POST /bookings/{id}/confirm (student) → 403", rs.status_code == 403, rs.status_code, rs.text[:200])

    # ---- 5b. Confirm permission: another mentor should get 403 ----
    if other_mentor:
        ro = requests.post(f"{BASE}/bookings/{booking_id}/confirm",
                           headers=auth_headers(other_mentor["access_token"]), timeout=20)
        _record("POST /bookings/{id}/confirm (other mentor not owner) → 403",
                ro.status_code == 403, ro.status_code, ro.text[:200])

    # ---- 6. Verify student notification for booking_confirmed ----
    rn = requests.get(f"{BASE}/notifications", headers=auth_headers(student_token), timeout=20)
    notif_data = rn.json() if rn.status_code == 200 else {}
    items = notif_data.get("items", [])
    confirmed_notif = [n for n in items if n.get("type") == "booking_confirmed" and n.get("booking_id") == booking_id]
    _record("GET /notifications (student) — booking_confirmed entry exists",
            len(confirmed_notif) >= 1, rn.status_code, confirmed_notif[:1],
            note=f"total={len(items)} confirmed_match={len(confirmed_notif)}")

    # ---- 7. Create a SECOND booking to test decline ----
    slot_start2 = (datetime.now(timezone.utc) + timedelta(days=3)).isoformat()
    slot_end2 = (datetime.now(timezone.utc) + timedelta(days=3, hours=1)).isoformat()
    cr2 = requests.post(f"{BASE}/bookings", json={
        "mentor_id": mentor_id,
        "slot_start_iso": slot_start2,
        "slot_end_iso": slot_end2,
        "topic": "MentorPortalTest — Decline Flow",
        "notes": "decline test",
    }, headers=auth_headers(student_token), timeout=20)
    booking2 = cr2.json() if cr2.status_code == 200 else None
    booking2_id = booking2.get("id") if booking2 else None
    print(f"Second booking_id={booking2_id}")

    # ---- 8. POST /bookings/{id}/decline as mentor ----
    if booking2_id:
        rd = requests.post(f"{BASE}/bookings/{booking2_id}/decline", headers=auth_headers(mentor_token), timeout=20)
        decline_ok = rd.status_code == 200 and (rd.json() or {}).get("booking", {}).get("status") == "cancelled"
        _record("POST /bookings/{id}/decline (mentor owner)", decline_ok, rd.status_code, rd.text[:300])

        # 8b. Re-decline by student → 403
        rd2 = requests.post(f"{BASE}/bookings/{booking2_id}/decline", headers=auth_headers(student_token), timeout=20)
        _record("POST /bookings/{id}/decline (student) → 403", rd2.status_code == 403, rd2.status_code, rd2.text[:200])

        # 8c. Verify student notification for booking_cancelled
        rn2 = requests.get(f"{BASE}/notifications", headers=auth_headers(student_token), timeout=20)
        items2 = (rn2.json() or {}).get("items", []) if rn2.status_code == 200 else []
        cancel_notif = [n for n in items2 if n.get("type") == "booking_cancelled" and n.get("booking_id") == booking2_id]
        _record("GET /notifications (student) — booking_cancelled entry exists",
                len(cancel_notif) >= 1, rn2.status_code, cancel_notif[:1],
                note=f"cancel_match={len(cancel_notif)}")

    # ---- 9. Decline non-existent booking → 404 ----
    rnf = requests.post(f"{BASE}/bookings/does-not-exist/decline",
                        headers=auth_headers(mentor_token), timeout=20)
    _record("POST /bookings/{bogus}/decline → 404", rnf.status_code == 404, rnf.status_code, rnf.text[:200])

    # ---- 10. POST /mentor/sessions ----
    session_payload = {
        "title": "Open Career Guidance Session",
        "topic": "AI/ML career roadmap",
        "scheduled_at": (datetime.now(timezone.utc) + timedelta(days=5)).isoformat(),
        "duration_minutes": 45,
        "max_attendees": 5,
    }
    rms = requests.post(f"{BASE}/mentor/sessions", json=session_payload,
                        headers=auth_headers(mentor_token), timeout=20)
    sess_ok = rms.status_code == 200 and (rms.json() or {}).get("session", {}).get("id")
    created_sess = (rms.json() or {}).get("session") if rms.status_code == 200 else None
    _record("POST /mentor/sessions (mentor)", bool(sess_ok), rms.status_code, rms.text[:400])
    sess_id = (created_sess or {}).get("id")

    # ---- 10b. POST /mentor/sessions as student → 403 ----
    rms_student = requests.post(f"{BASE}/mentor/sessions", json=session_payload,
                                 headers=auth_headers(student_token), timeout=20)
    _record("POST /mentor/sessions (student) → 403", rms_student.status_code == 403,
            rms_student.status_code, rms_student.text[:200])

    # ---- 11. GET /mentor/sessions/me ----
    rmg = requests.get(f"{BASE}/mentor/sessions/me", headers=auth_headers(mentor_token), timeout=20)
    sessions = (rmg.json() or {}).get("sessions", []) if rmg.status_code == 200 else []
    found = any(s.get("id") == sess_id for s in sessions) if sess_id else False
    _record("GET /mentor/sessions/me (mentor) — includes new session",
            rmg.status_code == 200 and found, rmg.status_code, sessions[:1],
            note=f"sessions={len(sessions)} contains_new={found}")

    # ---- 11b. GET /mentor/sessions/me as student → 403 ----
    rmg_s = requests.get(f"{BASE}/mentor/sessions/me", headers=auth_headers(student_token), timeout=20)
    _record("GET /mentor/sessions/me (student) → 403", rmg_s.status_code == 403,
            rmg_s.status_code, rmg_s.text[:200])

    # ---- 12. Regression: GET /mentors/{mentor_id}/reviews ----
    rrv = requests.get(f"{BASE}/mentors/{mentor_id}/reviews", timeout=20)
    body = rrv.json() if rrv.status_code == 200 else None
    has_shape = isinstance(body, dict) and "items" in body and "stats" in body
    _record("GET /mentors/{id}/reviews", rrv.status_code == 200 and has_shape,
            rrv.status_code, body, note=f"stats={(body or {}).get('stats')}")

    return summarize()


def summarize():
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    passed = sum(1 for r in results if r["pass"])
    total = len(results)
    print(f"PASSED: {passed}/{total}")
    print()
    failures = [r for r in results if not r["pass"]]
    if failures:
        print("FAILURES:")
        for f in failures:
            print(f"  ❌ {f['endpoint']}  status={f['status_code']}  body={f['body_sample']}")
    print("\nFULL REPORT:")
    print(json.dumps(results, indent=2, default=str))
    return passed, total


if __name__ == "__main__":
    p, t = main()
    sys.exit(0 if p == t else 1)
