/**
 * /career-ai — AI Career Roadmap (Phase 1 implementation).
 *
 * Sections rendered:
 *   1. Header  ............. title + Online pill + Regenerate button
 *   2. Overview metrics .... Skill Score · Profile Strength · AI Sessions · Streak
 *   3. Train with AI ....... 6 skill chips
 *   4. Skill scores ........ horizontal bars per skill (real %s from AI roadmap)
 *   5. 12-week timeline .... 5 cards (Weeks 1-2 → 9-10) generated by AI
 *   6. Build your profile .. 10-item action grid (status auto-derived from user)
 *
 * Backend:
 *   POST /ai/career-roadmap          — generate / cached
 *   POST /ai/career-roadmap {force:true} — regenerate
 *   GET  /users/me/completion        — for Profile Strength
 *   GET  /users/me/stats             — for AI Sessions / streak (graceful fallback)
 *
 * NOTE: "Skill Streak" is a derived metric from `daily_briefs` consecutive days;
 * if the backend doesn't expose it yet, we fall back to a sensible 0.
 */
import React, { useEffect, useMemo, useState, useCallback } from 'react';
import {
  View, Text, ScrollView, Pressable, StyleSheet, Platform,
  ActivityIndicator, useWindowDimensions,
} from 'react-native';
import { useRouter } from 'expo-router';
import {
  Target, User as UserIcon, Sparkles, Flame, RefreshCcw, ArrowLeft,
  MessageSquare, Briefcase, Star, Award, Folder, Link2, Code,
  CircleCheck as CheckCircle2, GitBranch, FileText, Mic, Search, ChevronRight, Calendar,
} from 'lucide-react-native';
import { useAuthStore } from '@/src/viewmodels/stores/authStore';
import { request } from '@/src/models/services/api';
import { useToast } from '@/src/views/components/Toast';

const C = {
  bg: '#0A0814',
  card: 'rgba(255,255,255,0.04)',
  cardSolid: '#1A1530',
  border: 'rgba(255,255,255,0.08)',
  text: '#fff',
  text2: 'rgba(255,255,255,0.65)',
  dim: 'rgba(255,255,255,0.4)',
  purple: '#7C3AED',
  purpleL: '#A78BFA',
  teal: '#14B8A6',
  blue: '#3B82F6',
  amber: '#F59E0B',
  red: '#EF4444',
  green: '#10B981',
  orange: '#F97316',
};
const FT = { med: 'DMSans_500Medium', bold: 'DMSans_700Bold', xbold: 'DMSans_800ExtraBold' };

interface RoadmapResp {
  target_role?: string;
  target_company_type?: string;
  progress_pct?: number;
  skill_scores?: Record<string, number>;
  weekly_plan?: Array<{ weeks: string; title: string; tasks: string[] }>;
  milestones_completed?: number[];
  suggestion?: string;
  generated_at?: string;
}

const SKILL_META: { key: string; label: string; color: string; Icon: any }[] = [
  { key: 'communication',  label: 'Communication',  color: '#A78BFA', Icon: MessageSquare },
  { key: 'soft_skills',    label: 'Soft Skills',    color: '#14B8A6', Icon: Star },
  { key: 'technical',      label: 'Technical Skills', color: '#5EEAD4', Icon: Code },
  { key: 'interview_prep', label: 'Interview Prep', color: '#3B82F6', Icon: Mic },
  { key: 'networking',     label: 'Networking',     color: '#C4B5FD', Icon: UserIcon },
  { key: 'leadership',     label: 'Leadership',     color: '#F59E0B', Icon: Award },
];

export default function CareerAIPage({ embedded = false }: { embedded?: boolean } = {}) {
  const router = useRouter();
  const toast = useToast();
  const user = useAuthStore((u) => u.user);
  const { width: winW } = useWindowDimensions();
  const cols = winW >= 1280 ? 4 : winW >= 900 ? 2 : 1;

  const [loading, setLoading] = useState(true);
  const [regen, setRegen] = useState(false);
  const [roadmap, setRoadmap] = useState<RoadmapResp>({});
  const [profileStrength, setProfileStrength] = useState(0);
  const [aiSessions, setAiSessions] = useState(0);
  const [skillStreak, setSkillStreak] = useState(0);
  const [completing, setCompleting] = useState<number | null>(null);

  const completed = useMemo<number[]>(() => roadmap.milestones_completed || [], [roadmap]);

  const toggleMilestone = useCallback(async (idx: number) => {
    if (completing !== null) return;
    setCompleting(idx);
    const wasDone = completed.includes(idx);
    try {
      const resp: any = await request(`/ai/career-roadmap/milestone/${idx}/complete`, {
        method: 'POST',
        body: { undo: wasDone },
      } as any);
      setRoadmap((r) => ({ ...r, milestones_completed: resp.milestones_completed || [] }));
      // Show toasts for new badge unlocks
      const nb = resp.new_badges || [];
      if (!wasDone && nb.length) {
        nb.forEach((b: any) => toast.success('🎉 New badge earned', `${b.label} — view it under Profile › Manage Profile › Earned Badges`));
      } else if (!wasDone) {
        const nm = resp.next_milestone;
        if (nm) toast.info('Milestone complete', `Next up — Week ${nm.weeks}: ${nm.title}`);
        else if (resp.next_phase_unlocked) toast.success('🎯 Roadmap complete!', 'Tap Regenerate to unlock the next 12-week phase.');
      }
    } catch (e: any) {
      toast.error('Could not update', e?.message || 'Please try again.');
    } finally {
      setCompleting(null);
    }
  }, [completed, completing, toast]);

  const reload = useCallback(async (force = false) => {
    if (force) setRegen(true); else setLoading(true);
    try {
      const [rm, comp, stats] = await Promise.all([
        request<RoadmapResp>('/ai/career-roadmap', { method: 'POST', body: { force } } as any).catch(() => ({})),
        request<any>('/users/me/completion').catch(() => ({})),
        request<any>('/users/me/stats').catch(() => ({})),
      ]);
      setRoadmap(rm || {});
      setProfileStrength(Number(comp?.percentage || 0));
      setAiSessions(Number(stats?.sessions_completed || 0));
      // Best-effort streak — if no backend value, infer from daily-brief existence
      setSkillStreak(Number(stats?.skill_streak || 0));
    } catch (e: any) {
      toast.error('Could not load', e?.message || 'Please try again.');
    } finally {
      setLoading(false); setRegen(false);
    }
  }, [toast]);

  useEffect(() => { reload(false); }, [reload]);

  const overallSkillScore = useMemo(() => {
    const ss = roadmap.skill_scores || {};
    const vals = SKILL_META.map((s) => Number(ss[s.key] || 0));
    if (!vals.length) return 0;
    return Math.round(vals.reduce((a, b) => a + b, 0) / vals.length);
  }, [roadmap]);

  // Build Your Profile checklist — status auto-derived from user object
  const builds = useMemo(() => {
    const u: any = user || {};
    return [
      { id: 'resume',    label: 'Resume',         desc: 'Upload or build resume',         done: !!u.resume_url || !!u.resume_data, Icon: FileText, color: C.purpleL,
        onPress: () => router.push('/me' as any) },
      { id: 'portfolio', label: 'Portfolio',      desc: 'Showcase your work',            done: !!u.portfolio_url || (Array.isArray(u.projects) && u.projects.length > 0), Icon: Briefcase, color: '#22D3EE',
        onPress: () => router.push('/student-portal' as any) },
      { id: 'skills',    label: 'Skills',         desc: 'List your expertise',           done: Array.isArray(u.skills) && u.skills.length >= 3, Icon: Star, color: '#F59E0B',
        onPress: () => router.push('/student-portal' as any) },
      { id: 'certs',     label: 'Certifications', desc: 'Add credentials',               done: Array.isArray(u.certifications) && u.certifications.length > 0, Icon: Award, color: '#10B981',
        onPress: () => router.push('/me' as any) },
      { id: 'projects',  label: 'Projects',       desc: 'Highlight achievements',        done: Array.isArray(u.projects) && u.projects.length > 0, Icon: Folder, color: '#A78BFA',
        onPress: () => router.push('/student-portal' as any) },
      { id: 'linkedin',  label: 'LinkedIn Boost', desc: 'Optimise LinkedIn profile',     done: !!u.linkedin_url, Icon: Link2, color: '#3B82F6',
        onPress: () => router.push('/student-portal' as any) },
      { id: 'mock',      label: 'Mock Interviews',desc: 'Practice with AI interviewer',  done: false, Icon: Code, color: '#EC4899',
        onPress: () => toast.info('Mock interviewer', 'AI mock interviewer coming this Friday!') },
      { id: 'cvreview',  label: 'CV Review',      desc: 'Get AI CV feedback',            done: false, Icon: CheckCircle2, color: '#5EEAD4',
        onPress: () => toast.info('CV Review', 'AI CV review queued for Phase 2.') },
      { id: 'github',    label: 'GitHub',         desc: 'Link GitHub profile',           done: !!u.github_url, Icon: GitBranch, color: '#E5E5E5',
        onPress: () => router.push('/student-portal' as any) },
      { id: 'letter',    label: 'Career Letter',  desc: 'AI-generated career summary',   done: false, Icon: Search, color: '#FB923C',
        onPress: () => toast.info('Career Letter', 'AI Letter Builder lands in Phase 2.') },
    ];
  }, [user, router, toast]);

  if (loading && !roadmap.weekly_plan) {
    return (
      <View style={[embedded ? s.embeddedShell : s.shell, { alignItems: 'center', justifyContent: 'center', padding: 40 }]}>
        <ActivityIndicator size="large" color={C.purpleL} />
        <Text style={{ color: C.text2, marginTop: 14, fontFamily: FT.med }}>Generating your roadmap…</Text>
      </View>
    );
  }

  const targetRole = roadmap.target_role || 'Software Engineer';
  const targetCo = roadmap.target_company_type || 'Top Tech Company';
  const progress = roadmap.progress_pct ?? 42;

  const Container: any = embedded ? View : ScrollView;
  const containerProps: any = embedded
    ? { style: s.embeddedShell }
    : { style: s.shell, contentContainerStyle: { padding: 22, paddingBottom: 80 } };

  return (
    <Container {...containerProps}>

      {/* Header */}
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 18 }}>
        {!embedded && (
          <Pressable onPress={() => router.back()} style={s.backBtn} testID="career-back">
            <ArrowLeft size={16} color={C.text} />
          </Pressable>
        )}
        <View style={{ flex: 1, minWidth: 0 }}>
          <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}>
            <Text style={s.title}>AI Career Roadmap</Text>
            <View style={s.onlinePill}>
              <View style={{ width: 6, height: 6, borderRadius: 3, backgroundColor: C.green }} />
              <Text style={s.onlinePillText}>Online · Personalised for you</Text>
            </View>
          </View>
          {!!roadmap.suggestion && (
            <Text style={s.suggest}>“{roadmap.suggestion}”</Text>
          )}
        </View>
        <Pressable
          onPress={() => reload(true)}
          disabled={regen}
          style={[s.regenBtn, regen && { opacity: 0.6 }]}
          testID="career-regen"
        >
          <RefreshCcw size={14} color="#fff" />
          <Text style={s.regenBtnText}>{regen ? 'Regenerating…' : 'Regenerate'}</Text>
        </Pressable>
      </View>

      {/* Overview metrics */}
      <View style={[s.grid, { gridTemplateColumns: `repeat(${cols}, minmax(0, 1fr))` } as any]}>
        <Metric label="OVERALL SKILL SCORE" value={`${overallSkillScore}%`} sub={`Across ${SKILL_META.length} skills`} Icon={Target} tint={C.purple} />
        <Metric label="PROFILE STRENGTH"    value={`${profileStrength}%`}  sub={profileStrength >= 100 ? 'All complete' : `${100 - profileStrength}% to go`} Icon={UserIcon} tint={C.teal} />
        <Metric label="AI SESSIONS"         value={`${aiSessions}`}        sub="This month" Icon={Sparkles} tint={C.orange} />
        <Metric label="SKILL STREAK"        value={`${skillStreak} days`}  sub={skillStreak ? 'Keep it up!' : 'Start your streak today'} Icon={Flame} tint={C.red} />
      </View>

      {/* Goal banner (target role + progress) */}
      <View style={s.goalCard}>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
          <View style={s.goalIcon}><Target size={16} color="#fff" /></View>
          <View style={{ flex: 1, minWidth: 0 }}>
            <Text style={s.goalLabel}>YOU&apos;RE {progress}% TOWARD YOUR GOAL</Text>
            <Text style={s.goalRole}>{targetRole} <Text style={{ color: C.purpleL }}>at a {targetCo}</Text></Text>
          </View>
        </View>
        <View style={s.goalBarTrack}>
          <View style={[s.goalBarFill, { width: `${Math.min(100, progress)}%` }]} />
        </View>
      </View>

      {/* Train with AI — skill chips */}
      <SectionTitle text="TRAIN WITH AI" />
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingVertical: 4 }}>
        {SKILL_META.map((sk) => {
          const pct = Number((roadmap.skill_scores || {})[sk.key] || 0);
          return (
            <Pressable key={sk.key} style={[s.skillChip, { borderColor: sk.color + '70' }]} testID={`skill-chip-${sk.key}`}>
              <View style={[s.skillChipDot, { backgroundColor: sk.color }]} />
              <Text style={s.skillChipText}>{sk.label}</Text>
              <Text style={[s.skillChipPct, { color: sk.color }]}>{pct}%</Text>
            </Pressable>
          );
        })}
      </ScrollView>

      {/* Skill scores horizontal bars */}
      <SectionTitle text="SKILL SCORES" />
      <View style={[s.card, { gap: 12 }]}>
        {SKILL_META.map((sk) => {
          const Icon = sk.Icon;
          const pct = Number((roadmap.skill_scores || {})[sk.key] || 0);
          return (
            <View key={sk.key} style={{ flexDirection: 'row', alignItems: 'center', gap: 12 }}>
              <View style={[s.skillIconBox, { backgroundColor: sk.color + '20', borderColor: sk.color + '50' }]}>
                <Icon size={14} color={sk.color} />
              </View>
              <View style={{ flex: 1, minWidth: 0 }}>
                <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 }}>
                  <Text style={s.skillRowLabel}>{sk.label}</Text>
                  <Text style={[s.skillRowPct, { color: sk.color }]}>{pct}%</Text>
                </View>
                <View style={s.barTrack}>
                  <View style={[s.barFill, { width: `${pct}%`, backgroundColor: sk.color }]} />
                </View>
              </View>
            </View>
          );
        })}
      </View>

      {/* 12-week roadmap timeline */}
      <SectionTitle text="12-WEEK AI CAREER ROADMAP" />
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 12, paddingVertical: 4 }}>
        {(roadmap.weekly_plan || []).map((wk, idx) => {
          const isDone = completed.includes(idx);
          const isNext = !isDone && idx === ((roadmap.weekly_plan || []).findIndex((_w, i) => !completed.includes(i)));
          return (
            <View
              key={`wk-${idx}`}
              style={[
                s.weekCard,
                isDone && { borderColor: 'rgba(16,185,129,0.55)', backgroundColor: 'rgba(16,185,129,0.08)' },
                isNext && { borderColor: 'rgba(167,139,250,0.55)', backgroundColor: 'rgba(167,139,250,0.10)' },
              ]}
              testID={`week-card-${idx}`}
            >
              <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                <Calendar size={12} color={isDone ? C.green : C.purpleL} />
                <Text style={[s.weekRange, isDone && { color: C.green }]}>Week {wk.weeks}</Text>
                {isNext && (
                  <View style={s.nextPill}>
                    <Text style={s.nextPillText}>NEXT</Text>
                  </View>
                )}
                {isDone && (
                  <View style={[s.nextPill, { backgroundColor: 'rgba(16,185,129,0.18)', borderColor: 'rgba(16,185,129,0.45)' }]}>
                    <CheckCircle2 size={10} color={C.green} />
                    <Text style={[s.nextPillText, { color: C.green }]}>DONE</Text>
                  </View>
                )}
              </View>
              <Text style={s.weekTitle}>{wk.title}</Text>
              <View style={{ gap: 6, marginTop: 8 }}>
                {wk.tasks.slice(0, 4).map((t, i) => (
                  <View key={i} style={{ flexDirection: 'row', alignItems: 'flex-start', gap: 6 }}>
                    <View style={[s.weekDot, { backgroundColor: isDone ? C.green : (isNext ? C.purpleL : C.dim) }]} />
                    <Text style={[s.weekTask, isDone && { textDecorationLine: 'line-through', color: C.dim }]}>{t}</Text>
                  </View>
                ))}
              </View>
              <Pressable
                onPress={() => toggleMilestone(idx)}
                disabled={completing !== null}
                style={[
                  s.milestoneBtn,
                  isDone ? s.milestoneBtnDone : (isNext ? s.milestoneBtnNext : s.milestoneBtnDefault),
                  completing !== null && { opacity: 0.6 },
                ]}
                testID={`week-complete-${idx}`}
              >
                {completing === idx ? (
                  <ActivityIndicator size="small" color="#fff" />
                ) : isDone ? (
                  <>
                    <CheckCircle2 size={13} color="#fff" />
                    <Text style={s.milestoneBtnText}>Completed · Tap to undo</Text>
                  </>
                ) : (
                  <>
                    <Target size={13} color="#fff" />
                    <Text style={s.milestoneBtnText}>Mark Milestone Complete</Text>
                  </>
                )}
              </Pressable>
            </View>
          );
        })}
      </ScrollView>

      {(roadmap.weekly_plan || []).length > 0 && completed.length >= (roadmap.weekly_plan || []).length && (
        <Pressable onPress={() => reload(true)} style={s.nextPhaseBanner} testID="generate-next-phase">
          <Sparkles size={16} color="#fff" />
          <View style={{ flex: 1 }}>
            <Text style={s.nextPhaseTitle}>🎯 Roadmap complete!</Text>
            <Text style={s.nextPhaseSub}>Tap to generate your next 12-week phase based on updated skills.</Text>
          </View>
          <RefreshCcw size={14} color="#fff" />
        </Pressable>
      )}

      {/* Build your profile grid */}
      <SectionTitle text="BUILD YOUR PROFILE" />
      <View style={[s.grid, { gridTemplateColumns: `repeat(${winW >= 1024 ? 5 : winW >= 600 ? 3 : 2}, minmax(0, 1fr))` } as any]}>
        {builds.map((b) => {
          const Icon = b.Icon;
          return (
            <Pressable key={b.id} onPress={b.onPress} style={s.buildCard} testID={`build-${b.id}`}>
              <View style={[s.buildIcon, { backgroundColor: b.color + '22', borderColor: b.color + '55' }]}>
                <Icon size={16} color={b.color} />
              </View>
              <View style={{ flex: 1, minWidth: 0 }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6 }}>
                  <Text style={s.buildLabel} numberOfLines={1}>{b.label}</Text>
                  {b.done && <CheckCircle2 size={11} color={C.green} />}
                </View>
                <Text style={s.buildDesc} numberOfLines={1}>{b.desc}</Text>
              </View>
              <ChevronRight size={14} color={C.dim} />
            </Pressable>
          );
        })}
      </View>

      <Text style={{ color: C.dim, fontFamily: FT.med, fontSize: 11, textAlign: 'center', marginTop: 22 }}>
        Roadmap last generated {roadmap.generated_at ? new Date(roadmap.generated_at).toLocaleString() : '—'} · Powered by Student Alumni AI
      </Text>
    </Container>
  );
}

/* ---------- helpers ---------- */
function Metric({ label, value, sub, Icon, tint }: { label: string; value: string; sub: string; Icon: any; tint: string }) {
  return (
    <View style={s.metricCard}>
      <View style={[s.metricIcon, { backgroundColor: tint + '22', borderColor: tint + '55' }]}>
        <Icon size={16} color={tint} />
      </View>
      <View style={{ marginTop: 10 }}>
        <Text style={s.metricLabel}>{label}</Text>
        <Text style={[s.metricValue, { color: tint }]}>{value}</Text>
        <Text style={s.metricSub}>{sub}</Text>
      </View>
    </View>
  );
}

function SectionTitle({ text }: { text: string }) {
  return <Text style={s.sectionTitle}>{text}</Text>;
}

const s = StyleSheet.create({
  shell: { flex: 1, backgroundColor: C.bg },
  embeddedShell: { flex: 1, backgroundColor: 'transparent' },

  backBtn: {
    width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center',
    backgroundColor: C.card, borderColor: C.border, borderWidth: 1,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : {}),
  },
  title: { color: C.text, fontFamily: FT.xbold, fontSize: 22, letterSpacing: -0.4 },
  onlinePill: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999,
    backgroundColor: 'rgba(16,185,129,0.12)', borderColor: 'rgba(16,185,129,0.45)', borderWidth: 1,
  },
  onlinePillText: { color: C.green, fontFamily: FT.bold, fontSize: 10 },
  suggest: { color: C.text2, fontFamily: FT.med, fontSize: 12, marginTop: 4, fontStyle: 'italic' },

  regenBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 14, height: 36, borderRadius: 10,
    backgroundColor: C.purple,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer', boxShadow: '0 6px 18px rgba(124,58,237,0.35)' } as any) : {}),
  },
  regenBtnText: { color: '#fff', fontFamily: FT.bold, fontSize: 12 },

  grid: { display: 'grid' as any, gap: 12, marginBottom: 14 },
  metricCard: {
    backgroundColor: C.card, borderColor: C.border, borderWidth: 1,
    borderRadius: 14, padding: 14, minHeight: 110,
  },
  metricIcon: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  metricLabel: { color: C.text2, fontFamily: FT.bold, fontSize: 9.5, letterSpacing: 1.0 },
  metricValue: { fontFamily: FT.xbold, fontSize: 24, marginTop: 3 },
  metricSub: { color: C.dim, fontFamily: FT.med, fontSize: 11 },

  goalCard: {
    backgroundColor: 'rgba(124,58,237,0.10)',
    borderColor: 'rgba(124,58,237,0.45)', borderWidth: 1,
    borderRadius: 14, padding: 16, marginBottom: 14,
  },
  goalIcon: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: C.purple },
  goalLabel: { color: C.purpleL, fontFamily: FT.bold, fontSize: 10, letterSpacing: 1.2 },
  goalRole: { color: C.text, fontFamily: FT.xbold, fontSize: 16, marginTop: 2 },
  goalBarTrack: { height: 8, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.06)', marginTop: 12, overflow: 'hidden' },
  goalBarFill: { height: '100%', backgroundColor: C.purpleL, borderRadius: 4 },

  sectionTitle: { color: C.text2, fontFamily: FT.xbold, fontSize: 11, letterSpacing: 1.2, marginTop: 18, marginBottom: 8 },

  skillChip: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : {}),
  },
  skillChipDot: { width: 8, height: 8, borderRadius: 4 },
  skillChipText: { color: C.text, fontFamily: FT.bold, fontSize: 12 },
  skillChipPct: { fontFamily: FT.xbold, fontSize: 12 },

  card: {
    backgroundColor: C.card, borderColor: C.border, borderWidth: 1,
    borderRadius: 14, padding: 16,
  },
  skillIconBox: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  skillRowLabel: { color: C.text, fontFamily: FT.bold, fontSize: 13 },
  skillRowPct: { fontFamily: FT.xbold, fontSize: 13 },
  barTrack: { height: 7, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.06)', overflow: 'hidden' },
  barFill: { height: '100%', borderRadius: 4 },

  weekCard: {
    width: 240,
    backgroundColor: C.card, borderColor: C.border, borderWidth: 1,
    borderRadius: 14, padding: 14,
  },
  weekRange: { color: C.purpleL, fontFamily: FT.bold, fontSize: 10, letterSpacing: 0.6 },
  weekTitle: { color: C.text, fontFamily: FT.xbold, fontSize: 14, marginTop: 4 },
  weekDot: { width: 6, height: 6, borderRadius: 3, marginTop: 6 },
  weekTask: { flex: 1, color: C.text2, fontFamily: FT.med, fontSize: 11.5, lineHeight: 16 },
  nextPill: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 6, paddingVertical: 2, borderRadius: 999,
    backgroundColor: 'rgba(167,139,250,0.18)', borderColor: 'rgba(167,139,250,0.45)', borderWidth: 1,
    marginLeft: 'auto',
  },
  nextPillText: { color: C.purpleL, fontFamily: FT.xbold, fontSize: 9, letterSpacing: 0.5 },
  milestoneBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, marginTop: 12, height: 34, borderRadius: 8,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : {}),
  },
  milestoneBtnDefault: { backgroundColor: 'rgba(255,255,255,0.06)', borderColor: 'rgba(255,255,255,0.10)', borderWidth: 1 },
  milestoneBtnNext: { backgroundColor: C.purple },
  milestoneBtnDone: { backgroundColor: C.green },
  milestoneBtnText: { color: '#fff', fontFamily: FT.bold, fontSize: 11.5 },
  nextPhaseBanner: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    padding: 14, marginTop: 14, borderRadius: 14,
    backgroundColor: 'rgba(167,139,250,0.14)', borderColor: 'rgba(167,139,250,0.50)', borderWidth: 1,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : {}),
  },
  nextPhaseTitle: { color: '#fff', fontFamily: FT.xbold, fontSize: 13 },
  nextPhaseSub: { color: C.text2, fontFamily: FT.med, fontSize: 11.5, marginTop: 2 },

  buildCard: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    backgroundColor: C.card, borderColor: C.border, borderWidth: 1,
    borderRadius: 12, padding: 12,
    ...(Platform.OS === 'web' ? ({ cursor: 'pointer' } as any) : {}),
  },
  buildIcon: { width: 34, height: 34, borderRadius: 9, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  buildLabel: { color: C.text, fontFamily: FT.bold, fontSize: 12.5 },
  buildDesc:  { color: C.text2, fontFamily: FT.med, fontSize: 10.5, marginTop: 2 },
});
